### ISSUE TITLE
Unnecessary Padding

### ISSUE THREAD

**Issue by IsraaSulaiman** [ca-g7/MMSH_Team#34]
Hi guys!
Well done. Your portfolio website looks good. 

If you noticed, there is a padding at the top of the page. See?
![Screenshot from 2019-07-03 23-04-06](https://user-images.githubusercontent.com/35868173/60621670-ee720700-9de6-11e9-8a13-fedaa1ce7888.png)
 
To solve the problem, remove padding from the style of your nav
```css
nav{
    display:flex;
    align-items: center;
    justify-content: space-around;
    padding:0.25rem;
    position: sticky;
    top:0;
    z-index:1;
}
```
