### ISSUE TITLE
Team pictures are always stretched?

### ISSUE THREAD

**Issue by Amoodaa** [ca-g7/MMSH_Team#42]
have you considered a better way to do it?, since it wont look the same on all devices, some better way i found was 
```css
.myImg {  object-fit: cover;  width: 320px;  height: 180px;}
```
and actually using object fit cover works fine if u changed the breakpoint of the tablet a little bit
from [this article](https://www.freecodecamp.org/news/time-saving-css-techniques-to-create-responsive-images-ebb1e84f90d5/)
